# About the data
- This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.
#### InvoiceNo:
-  Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. 
#### StockCode: 
- Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.
#### Description:
- Product (item) name. Nominal.
#### Quantity:
- The quantities of each product (item) per transaction. Numeric.	
#### InvoiceDate:
- Invoice Date and time. Numeric, the day and time when each transaction was generated.
#### UnitPrice:
- Unit price. Numeric, Product price per unit in sterling.
#### CustomerID:
- Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.
#### Country:
- Country name. Nominal, the name of the country where each customer resides.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Online Retail.xlsx')

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.sample(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
325655,565449,23198,PANTRY MAGNETIC SHOPPING LIST,12,2011-09-04 15:21:00,1.45,16057.0,United Kingdom
405180,571713,21352,EUCALYPTUS & PINECONE WREATH,2,2011-10-18 16:58:00,5.79,NaN,United Kingdom
467231,576339,22792,FLUTED ANTIQUE CANDLE HOLDER,2,2011-11-14 15:27:00,1.63,14096.0,United Kingdom
123847,546917,22191,IVORY DINER WALL CLOCK,2,2011-03-18 09:17:00,8.50,14911.0,EIRE
297323,562935,23322,LARGE WHITE HEART OF WICKER,40,2011-08-10 17:11:00,2.55,14156.0,EIRE
116560,546252,21668,RED STRIPE CERAMIC DRAWER KNOB,12,2011-03-10 14:42:00,1.25,14930.0,Channel Islands
298782,563037,20728,LUNCH BAG CARS BLUE,10,2011-08-11 15:02:00,1.65,12362.0,Belgium
175544,551966,23150,IVORY SWEETHEART SOAP DISH,1,2011-05-05 13:14:00,2.49,15356.0,United Kingdom
534629,581164,23321,SMALL WHITE HEART OF WICKER,6,2011-12-07 14:34:00,1.65,14395.0,United Kingdom
254189,559298,22419,LIPSTICK PEN RED,12,2011-07-07 12:38:00,0.42,12471.0,Germany
512482,579512,23156,SET OF 5 MINI GROCERY MAGNETS,1,2011-11-29 16:47:00,4.13,NaN,United Kingdom
316948,564757,22423,REGENCY CAKESTAND 3 TIER,4,2011-08-30 10:36:00,24.96,NaN,United Kingdom
887,536488,84558A,3D DOG PICTURE PLAYING CARDS,1,2010-12-01 12:31:00,2.95,17897.0,United Kingdom
132175,547656,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,1,2011-03-24 12:53:00,2.95,13263.0,United Kingdom
389068,570465,21790,VINTAGE SNAP CARDS,1,2011-10-10 16:02:00,1.63,NaN,United Kingdom

In [5]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [6]:
df.shape

(541909, 8)

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [10]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303