In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Online Retail.xlsx')

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
df.dropna(inplace= True)

In [6]:
df.shape

(406829, 8)

In [7]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5225)

In [9]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [10]:
 df[df['Quantity'] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [11]:
df =df[df['UnitPrice'] > 0]

In [12]:
df.shape

(406789, 8)

In [13]:
# Datatype conversion 
df['CustomerID'] = df['CustomerID'].astype(int)

In [14]:
#Feature engineering creating new feature TotalAmount 
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

In [15]:
#Creating new feature IsCancelled
df['IsCancelled']= df['InvoiceNo'].astype(str).str.startswith('C')

In [16]:
purchase_df = df[(~df['IsCancelled']) & (df['Quantity'] > 0 )].copy()

In [17]:
purchase_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount,IsCancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,False
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20,False
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60,False
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60,False
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60,False
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85,False

In [18]:
purchase_df.info()

<class 'pandas.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[us]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  int64
 7   Country      397884 non-null  str
 8   TotalAmount  397884 non-null  float64
 9   IsCancelled  397884 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(2), int64(2), object(3), str(1)
memory usage: 30.7+ MB

# Feature Engineering

In [19]:
reference_date = purchase_df["InvoiceDate"].max() + pd.Timedelta(days=1)

In [20]:
recency = purchase_df.groupby("CustomerID").agg(
    Recency=("InvoiceDate", lambda x:
             (reference_date - x.max()).days)
)

In [21]:
frequency = purchase_df.groupby("CustomerID").agg(
    Frequency=("InvoiceNo", "nunique")
)

In [22]:
monetary = purchase_df.groupby("CustomerID").agg(
    Monetary=("TotalAmount", "sum")
)

In [23]:
customer_features = purchase_df.groupby("CustomerID").agg(
    
    # Monetary features
    Total_Spend=("TotalAmount", "sum"),
    Average_Order_Value=("TotalAmount", "mean"),
    Median_Order_Value=("TotalAmount", "median"),
    Maximum_Order_Value=("TotalAmount", "max"),
    Minimum_Order_Value=("TotalAmount", "min"),
    
    # Quantity features
    Total_Quantity=("Quantity", "sum"),
    Average_Quantity=("Quantity", "mean"),
    Maximum_Quantity=("Quantity", "max"),
    Minimum_Quantity=("Quantity", "min"),
    
    # Transaction features
    Total_Transactions=("InvoiceNo", "nunique"),
    Unique_Products=("StockCode", "nunique"),
    Unique_Descriptions=("Description", "nunique"),
    
    # Price features
    Average_Unit_Price=("UnitPrice", "mean"),
    Maximum_Unit_Price=("UnitPrice", "max"),
    Minimum_Unit_Price=("UnitPrice", "min"),
    
    # Geographic behavior
    Countries=("Country", "nunique"),
    
    # Temporal behavior
    First_Purchase=("InvoiceDate", "min"),
    Last_Purchase=("InvoiceDate", "max"),
    
).reset_index()

In [24]:
# Recency -> How recenctly did the customer purchase
customer_features["Recency"] = (
    reference_date -
    customer_features["Last_Purchase"]
).dt.days

In [25]:
# Customer lifetime
customer_features["Customer_Lifetime"] = (
    customer_features["Last_Purchase"] -
    customer_features["First_Purchase"]
).dt.days

In [26]:
# Spend per transaction
customer_features["Spend_per_Transaction"] = (
    customer_features["Total_Spend"] /
    customer_features["Total_Transactions"]
)

In [27]:
# Quantity per transaction
customer_features["Quantity_per_Transaction"] = (
    customer_features["Total_Quantity"] /
    customer_features["Total_Transactions"]
)

In [28]:
# Product diversity
customer_features["Product_Diversity"] = (
    customer_features["Unique_Products"] /
    customer_features["Total_Transactions"]
)

In [29]:
# Cancellation features
cancellation_features = df.groupby("CustomerID").agg(
    Total_Invoices=("InvoiceNo", "nunique"),
    Cancelled_Transactions=("IsCancelled", "sum")
)

In [30]:
# Cancellation rate
cancellation_features["Cancellation_Rate"] = (
    cancellation_features["Cancelled_Transactions"] /
    cancellation_features["Total_Invoices"]
)

In [31]:
# Merging two dataset
customer_features = customer_features.merge(
    cancellation_features[["Cancellation_Rate"]],
    on="CustomerID",
    how="left"
)

In [32]:
#Fill nane values of Canellaion rate with 0
customer_features["Cancellation_Rate"] = (
    customer_features["Cancellation_Rate"].fillna(0)
)

In [33]:
customer_features

,CustomerID,Total_Spend,Average_Order_Value,Median_Order_Value,Maximum_Order_Value,Minimum_Order_Value,Total_Quantity,Average_Quantity,Maximum_Quantity,Minimum_Quantity,...,Minimum_Unit_Price,Countries,First_Purchase,Last_Purchase,Recency,Customer_Lifetime,Spend_per_Transaction,Quantity_per_Transaction,Product_Diversity,Cancellation_Rate
0,12346,77183.60,77183.600000,77183.60,77183.60,77183.60,74215,74215.000000,74215,74215,...,1.04,1,2011-01-18 10:01:00,2011-01-18 10:01:00,326,0,77183.600000,74215.000000,1.000000,0.500000
1,12347,4310.00,23.681319,17.00,249.60,5.04,2458,13.505495,240,2,...,0.25,1,2010-12-07 14:57:00,2011-12-07 15:52:00,2,365,615.714286,351.142857,14.714286,0.000000
2,12348,1797.24,57.975484,41.76,240.00,13.20,2341,75.516129,144,1,...,0.29,1,2010-12-16 19:09:00,2011-09-25 13:13:00,75,282,449.310000,585.250000,5.500000,0.000000
3,12349,1757.55,24.076027,17.70,300.00,6.64,631,8.643836,36,1,...,0.42,1,2011-11-21 09:51:00,2011-11-21 09:51:00,19,0,1757.550000,631.000000,73.000000,0.000000
4,12350,334.40,19.670588,19.80,40.00,8.50,197,11.588235,24,1,...,0.85,1,2011-02-02 16:01:00,2011-02-02 16:01:00,310,0,334.400000,197.000000,17.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4333,18280,180.60,18.060000,17.70,23.70,14.85,45,4.500000,8,2,...,2.55,1,2011-03-07 09:52:00,2011-03-07 09:52:00,278,0,180.600000,45.000000,10.000000,0.000000
4334,18281,80.82,11.545714,15.30,16.95,5.04,54,7.714286,12,1,...,0.42,1,2011-06-12 10:53:00,2011-06-12 10:53:00,181,0,80.820000,54.000000,7.000000,0.000000
4335,18282,178.05,14.837500,13.71,25.50,5.04,103,8.583333,48,1,...,0.29,1,2011-08-05 13:35:00,2011-12-02 11:43:00,8,118,89.025000,51.500000,6.000000,0.333333
4336,18283,2094.88,2.771005,2.08,20.80,0.29,1397,1.847884,13,1,...,0.29,1,2011-01-06 14:14:00,2011-12-06 12:02:00,4,333,130.930000,87.312500,16.437500,0.000000
4337,18287,1837.28,26.246857,18.72,87.00,5.04,1586,22.657143,60,4,...,0.29,1,2011-05-22 10:39:00,2011-10-28 09:29:00,43,158,612.426667,528.666667,19.666667,0.000000

In [35]:
customer_features.to_csv('preprocessed.csv',index= False)